spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      forwarded:
        enabled: true
      httpclient:
        websocket:
          max-frame-payload-length: 9999999
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            exposed-headers:
            - "Upgrade"
            - "Connection"
      routes:
        - id: websocket_route
          uri: ws://localhost:8088
          predicates:
            - Path=/ws/**
        - id: websocket_route_http
          uri: lb://PRICES
          predicates:
          - Path=/prices/**

        - id: exchange
          uri: lb://STOCK-EXCHANGE
          predicates:
            - Path=/shares/**
 
        - id: portfolio
          uri: lb://PORTFOLIOS
          predicates:
            - Path=/holdings/**

        - id: watchlist
          uri: lb://PORTFOLIOS
          predicates:
            - Path=/watchlist/**

        - id: registration
          uri: lb://REGISTER
          predicates:
            - Path=/api/auth/**

        - id: trading
          uri: lb://TRADING
          predicates:
            - Path=/trade/**

               
server:
  port: 8888

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.socket: DEBUG
    org.springframework.messaging: DEBUG